#[[redirects]]
#  from = "/styles/*"
#  to = "https://focused-beaver-3cc79d.netlify.com/styles/:splat"
#  status = 200
#  force = true
#  headers = {X-From = "Netlify"}
#
#[[redirects]]
#  from = "/elements/*"
#  to = "https://focused-beaver-3cc79d.netlify.com/elements/:splat"
#  status = 200
#  force = true
#  headers = {X-From = "Netlify"}
#
#[[redirects]]
#  from = "/images/*"
#  to = "https://focused-beaver-3cc79d.netlify.com/images/:splat"
#  status = 200
#  force = true
#  headers = {X-From = "Netlify"}
#
#[[redirects]]
#  from = "/scripts/*"
#  to = "https://focused-beaver-3cc79d.netlify.com/scripts/:splat"
#  status = 200
#  force = true
#  headers = {X-From = "Netlify"}
#
#[[redirects]]
#  from = "/site.webmanifest"
#  to = "https://focused-beaver-3cc79d.netlify.com/site.webmanifest"
#  status = 200
#  force = true
#  headers = {X-From = "Netlify"}
